# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  pro-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/transcribot:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/transcribot:latest
      - name: Set up Kubernetes CLI
        uses: azure/setup-kubectl@v4
        with:
          version: latest  
      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest  
      - name: Configure Kubernetes credentials
        run: |
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml

      - name: Deploy Helm chart
        run: |
          helm upgrade --install transcribot chart/ \
            --namespace transcribot \
            --create-namespace \
            --set image.repository=${{ secrets.DOCKER_HUB_USERNAME }}/transcribot \
            --set image.tag=latest
            s