# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  pro-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_ACTIONS }}
          name: github-actions
          known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy code
        run: rsync -avz --delete --exclude '.git/' --exclude 'data/' -e "ssh -i ~/.ssh/github-actions" . ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }} --exclude=/.env

      - name: Build image transcribot:latest
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY_GITHUB_ACTIONS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            docker compose build
            docker compose down
            docker compose up -d
